-- APS schedule analysis platform schema (MySQL 8+ recommended)
-- Notes:
-- - Database creation is handled by scripts/init_mysql.py
-- - All tables use utf8mb4 for Chinese text and emojis in notes/paths if any.

CREATE TABLE IF NOT EXISTS schedule_run (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_code VARCHAR(128) NOT NULL,
  profile_name VARCHAR(64) NULL,
  input_order_file VARCHAR(1024) NULL,
  input_steel_file VARCHAR(1024) NULL,
  result_file_path VARCHAR(1024) NULL,
  acceptance VARCHAR(64) NULL,
  failure_mode VARCHAR(64) NULL,
  routing_feasible TINYINT(1) NULL,
  analysis_only TINYINT(1) NULL,
  official_exported TINYINT(1) NULL,
  analysis_exported TINYINT(1) NULL,
  total_orders INT NULL,
  scheduled_orders INT NULL,
  unscheduled_orders INT NULL,
  dropped_orders INT NULL,
  scheduled_tons DOUBLE NULL,
  unscheduled_tons DOUBLE NULL,
  template_build_seconds DOUBLE NULL,
  joint_master_seconds DOUBLE NULL,
  fallback_total_seconds DOUBLE NULL,
  total_run_seconds DOUBLE NULL,
  evidence_level VARCHAR(64) NULL,
  best_candidate_available TINYINT(1) NULL,
  best_candidate_type VARCHAR(64) NULL,
  best_candidate_objective DOUBLE NULL,
  best_candidate_unroutable_slot_count INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_schedule_run_code (run_code),
  UNIQUE KEY uk_schedule_run_result_file_path (result_file_path),
  KEY idx_schedule_run_created_at (created_at),
  KEY idx_schedule_run_profile (profile_name),
  KEY idx_schedule_run_acceptance (acceptance),
  KEY idx_schedule_run_failure_mode (failure_mode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule_order_result (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NOT NULL,
  order_id VARCHAR(128) NOT NULL,
  line VARCHAR(32) NULL,
  slot_no INT NULL,
  candidate_position INT NULL,
  tons DOUBLE NULL,
  width INT NULL,
  thickness DOUBLE NULL,
  temp_min DOUBLE NULL,
  temp_max DOUBLE NULL,
  steel_group VARCHAR(256) NULL,
  line_capability VARCHAR(32) NULL,
  candidate_status VARCHAR(64) NULL,
  drop_flag TINYINT(1) NULL,
  dominant_drop_reason VARCHAR(64) NULL,
  secondary_reasons TEXT NULL,
  slot_unroutable_flag TINYINT(1) NULL,
  slot_route_risk_score DOUBLE NULL,
  analysis_only TINYINT(1) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_order_result_run_id (run_id),
  KEY idx_order_result_order_id (order_id),
  KEY idx_order_result_line_slot (line, slot_no),
  KEY idx_order_result_created_at (created_at),
  CONSTRAINT fk_order_result_run_id FOREIGN KEY (run_id) REFERENCES schedule_run(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule_slot_summary (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NOT NULL,
  line VARCHAR(32) NOT NULL,
  slot_no INT NOT NULL,
  slot_order_count INT NULL,
  slot_tons DOUBLE NULL,
  order_count_over_cap INT NULL,
  template_coverage_ratio DOUBLE NULL,
  missing_template_edge_count INT NULL,
  zero_in_orders INT NULL,
  zero_out_orders INT NULL,
  width_span INT NULL,
  thickness_span DOUBLE NULL,
  steel_group_count INT NULL,
  pair_gap_proxy DOUBLE NULL,
  span_risk DOUBLE NULL,
  degree_risk DOUBLE NULL,
  isolated_order_penalty DOUBLE NULL,
  slot_route_risk_score DOUBLE NULL,
  dominant_unroutable_reason VARCHAR(64) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_slot_summary (run_id, line, slot_no),
  KEY idx_slot_summary_run_id (run_id),
  KEY idx_slot_summary_line_slot (line, slot_no),
  KEY idx_slot_summary_created_at (created_at),
  CONSTRAINT fk_slot_summary_run_id FOREIGN KEY (run_id) REFERENCES schedule_run(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule_violation_summary (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NOT NULL,
  direct_reverse_step_violation_count INT NULL,
  virtual_attach_reverse_violation_count INT NULL,
  period_reverse_count_violation_count INT NULL,
  bridge_count_violation_count INT NULL,
  invalid_virtual_spec_count INT NULL,
  candidate_unroutable_slot_count INT NULL,
  candidate_bad_slot_count INT NULL,
  candidate_zero_in_order_count INT NULL,
  candidate_zero_out_order_count INT NULL,
  hard_cap_not_enforced TINYINT(1) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_violation_summary_run_id (run_id),
  KEY idx_violation_summary_run_id (run_id),
  CONSTRAINT fk_violation_summary_run_id FOREIGN KEY (run_id) REFERENCES schedule_run(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule_bridge_drop_summary (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NOT NULL,
  selected_direct_edge_count INT NULL,
  selected_real_bridge_edge_count INT NULL,
  selected_virtual_bridge_edge_count INT NULL,
  direct_edge_ratio DOUBLE NULL,
  real_bridge_ratio DOUBLE NULL,
  virtual_bridge_ratio DOUBLE NULL,
  max_bridge_count_used INT NULL,
  avg_virtual_count DOUBLE NULL,
  dropped_reason_histogram_json JSON NULL,
  dropped_order_count INT NULL,
  dropped_tons DOUBLE NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_bridge_drop_summary_run_id (run_id),
  KEY idx_bridge_drop_summary_run_id (run_id),
  CONSTRAINT fk_bridge_drop_summary_run_id FOREIGN KEY (run_id) REFERENCES schedule_run(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule_transition_metric (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id BIGINT NOT NULL,
  line VARCHAR(32) NOT NULL,
  slot_no INT NOT NULL,
  seq_no INT NOT NULL,
  from_order_id VARCHAR(128) NULL,
  to_order_id VARCHAR(128) NULL,
  from_temp_mid DOUBLE NULL,
  to_temp_mid DOUBLE NULL,
  temp_overlap DOUBLE NULL,
  temp_jump DOUBLE NULL,
  from_thickness DOUBLE NULL,
  to_thickness DOUBLE NULL,
  thickness_jump DOUBLE NULL,
  from_width INT NULL,
  to_width INT NULL,
  width_jump INT NULL,
  reverse_flag TINYINT(1) NULL,
  bridge_type VARCHAR(64) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY idx_transition_metric_run_id (run_id),
  KEY idx_transition_metric_line_slot (run_id, line, slot_no),
  KEY idx_transition_metric_created_at (created_at),
  CONSTRAINT fk_transition_metric_run_id FOREIGN KEY (run_id) REFERENCES schedule_run(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

