from __future__ import annotations

from enum import Enum


class RuleKey(str, Enum):
    LINE_COMPATIBILITY = "LINE_COMPATIBILITY"
    TEMPERATURE_OVERLAP = "TEMPERATURE_OVERLAP"
    WIDTH_TRANSITION = "WIDTH_TRANSITION"
    THICKNESS_TRANSITION = "THICKNESS_TRANSITION"
    CROSS_GROUP_BRIDGE = "CROSS_GROUP_BRIDGE"
    CAMPAIGN_TON_MAX = "CAMPAIGN_TON_MAX"
    CAMPAIGN_TON_MIN = "CAMPAIGN_TON_MIN"
    REVERSE_WIDTH_COUNT = "REVERSE_WIDTH_COUNT"
    REVERSE_WIDTH_TOTAL = "REVERSE_WIDTH_TOTAL"
    VIRTUAL_USAGE = "VIRTUAL_USAGE"
    VIRTUAL_RATIO = "VIRTUAL_RATIO"
